# Generated by Django 5.1.1 on 2025-03-14 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='favourited',
        ),
    ]
