# Generated by Django 5.1.1 on 2025-03-08 20:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lessons/%Y/%m/%d/')),
                ('markdown_content', models.TextField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('gcs_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
