# Generated by Django 5.1.1 on 2025-03-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_gcs_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gcs_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
