# Generated by Django 5.1.1 on 2025-03-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_gcs_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='markdown_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='view_count',
        ),
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(default='English', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='gcs_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='original_filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='pdf_file',
            field=models.CharField(max_length=500),
        ),
    ]
