# Generated by Django 5.1.1 on 2025-03-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_markdown_content_remove_post_view_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='original_filename',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
    ]
