# Generated by Django 5.1.1 on 2025-03-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_original_filename_post_title_and_more'),
        ('users', '0011_remove_favourites_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_posts', to='users.user'),
        ),
    ]
