# Generated by Django 5.1.1 on 2024-09-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
