# Generated by Django 5.1.1 on 2024-10-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
