# Generated by Django 5.1.1 on 2025-03-09 12:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pdf_file', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('subject', models.CharField(default='English', max_length=255)),
                ('gcs_url', models.URLField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='users.user')),
            ],
        ),
    ]
