# Generated by Django 5.1.1 on 2025-03-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_name_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
