# Generated by Django 5.1.1 on 2025-03-14 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_favourites_updated_at_remove_user_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='original_filename',
        ),
    ]
